Repository InternetEthan/dnd-builder, pull requests merged in 2023-11, with the labels that each got.

#21 Updated schema.sql
  db/schema.sql
Labels: additions

#18 Created .md file for pseudo code
  pseudoCode.md
Labels: additions

#26 css styling
  config/connection.js
  public/css/style.css
  views/layouts/main.handlebars
  views/login.handlebars
Labels: documentation

#27 connected character creation handlebar + route + script
  controllers/api/characterRoutes.js
  public/js/charactercreate.js
  views/characterform.handlebars
Labels: documentation, major, coding

#29 linked create a class form
  controllers/homeRoutes.js
  views/createCharacter.handlebars
  views/layouts/main.handlebars
Labels: coding

#32 Nataniel
  controllers/api/characterRoutes.js
  controllers/api/index.js
  public/js/charactercreate.js
  test.js
  utils/auth.js
  utils/helpers.js
  views/createCharacter.handlebars
  views/login.handlebars
Labels: documentation, coding

#41 cleaning up the profile, creating character adn log in page
  views/createCharacter.handlebars
  views/login.handlebars
  views/profile.handlebars
Labels: documentation, coding, polish

#42 UI formatting
  models/character.js
  seeds/characterData.JSON
  seeds/userData.JSON
  views/characterSheet.handlebars
Labels: documentation, major, coding

#54 finally fixed
  README.md
  package-lock.json
  server.js
Labels: additions, polish, commit monster
